export const products = [
  {
    id: 'spring-elegance',
    name: 'Spring Elegance',
    price: 35,
    category: 'spring',
    popular: 100,
    image: './assets/spring-elegance-large.jpg',
    cardImage: './assets/top-spring.jpg',
    description:
      'Each stem is carefully selected to create a bouquet that radiates freshness, elegance, and the gentle charm of spring. Whether you’re celebrating a birthday, sending love, or simply brightening someone’s day, this arrangement is sure to bring warm smiles and lasting impressions.',
    bestseller: true,
  },
  {
    id: 'berry-chic',
    name: 'Berry Chic',
    price: 40,
    category: 'romantic',
    popular: 96,
    image: './assets/top-berry.jpg',
    cardImage: './assets/top-berry.jpg',
    description:
      'A graceful bouquet with berry tones, soft petals and a refined silhouette. Perfect for a romantic gift or a warm personal celebration.',
    bestseller: true,
  },
  {
    id: 'lavender-dream',
    name: 'Lavender Dream',
    price: 55,
    category: 'premium',
    popular: 92,
    image: './assets/top-lavender.jpg',
    cardImage: './assets/top-lavender.jpg',
    description:
      'A premium composition with lavender accents and deep garden textures. It feels calm, elegant and memorable.',
    bestseller: true,
  },
  {
    id: 'peach-meadow',
    name: 'Peach Meadow',
    price: 55,
    category: 'gift',
    popular: 89,
    image: './assets/peach-meadow.jpg',
    cardImage: './assets/peach-meadow.jpg',
    description: 'Soft peach shades, bright greens and fresh garden flowers gathered into a tender everyday gift.',
  },
  {
    id: 'blush-romance',
    name: 'Blush Romance',
    price: 34,
    category: 'romantic',
    popular: 88,
    image: './assets/blush-romance.jpg',
    cardImage: './assets/blush-romance.jpg',
    description: 'A delicate romantic bouquet with airy blush shades and a natural hand-tied look.',
  },
  {
    id: 'pastel-garden',
    name: 'Pastel Garden',
    price: 40,
    category: 'spring',
    popular: 86,
    image: './assets/pastel-garden.jpg',
    cardImage: './assets/pastel-garden.jpg',
    description: 'Pastel flowers arranged with garden greenery for a fresh and soft seasonal mood.',
  },
  {
    id: 'tulip-charm',
    name: 'Tulip Charm',
    price: 61,
    category: 'premium',
    popular: 85,
    image: './assets/tulip-charm.jpg',
    cardImage: './assets/tulip-charm.jpg',
    description: 'A bright premium bouquet with tulips and expressive accents for a confident floral gift.',
  },
  {
    id: 'berry-bloom',
    name: 'Berry Bloom',
    price: 32,
    category: 'romantic',
    popular: 83,
    image: './assets/berry-bloom.jpg',
    cardImage: './assets/berry-bloom.jpg',
    description: 'Deep berry tones and textured flowers in a compact bouquet full of warmth.',
  },
  {
    id: 'sweet-whisper',
    name: 'Sweet Whisper',
    price: 40,
    category: 'gift',
    popular: 82,
    image: './assets/sweet-whisper.jpg',
    cardImage: './assets/sweet-whisper.jpg',
    description: 'A soft basket arrangement with pink shades, gentle whites and a cozy gift feeling.',
  },
  {
    id: 'field-joy',
    name: 'Field Joy',
    price: 49,
    category: 'spring',
    popular: 80,
    image: './assets/field-joy.jpg',
    cardImage: './assets/field-joy.jpg',
    description: 'A lively bouquet with a field-inspired color mix and a sunny, cheerful personality.',
  },
  {
    id: 'soft-bloom',
    name: 'Soft Bloom',
    price: 37,
    category: 'gift',
    popular: 78,
    image: './assets/soft-bloom.jpg',
    cardImage: './assets/soft-bloom.jpg',
    description: 'A modern wrapped bouquet with soft petals and calm muted shades.',
  },
  {
    id: 'rose-morning',
    name: 'Rose Morning',
    price: 45,
    category: 'romantic',
    popular: 74,
    image: './assets/top-berry.jpg',
    cardImage: './assets/top-berry.jpg',
    description: 'Romantic roses in a fresh morning palette, created for warm messages and special days.',
  },
  {
    id: 'garden-light',
    name: 'Garden Light',
    price: 42,
    category: 'spring',
    popular: 72,
    image: './assets/peach-meadow.jpg',
    cardImage: './assets/peach-meadow.jpg',
    description: 'Light garden flowers with a bright, natural shape and a soft seasonal touch.',
  },
  {
    id: 'premium-muse',
    name: 'Premium Muse',
    price: 68,
    category: 'premium',
    popular: 70,
    image: './assets/tulip-charm.jpg',
    cardImage: './assets/tulip-charm.jpg',
    description: 'An expressive premium bouquet with rich colors and a clean modern presentation.',
  },
  {
    id: 'tender-gift',
    name: 'Tender Gift',
    price: 38,
    category: 'gift',
    popular: 69,
    image: './assets/sweet-whisper.jpg',
    cardImage: './assets/sweet-whisper.jpg',
    description: 'A tender gift bouquet for birthdays, thank-you notes and simple warm surprises.',
  },
];
